/* ===================REFERENCE=================== */
console.group("REFERENCE");
console.log("favicon ->", "https://svgsilh.com/es/4caf50/image/1327960.html");
console.log("imagen1 ->", "https://i.ytimg.com/vi/Vcl2Rje_6w0/maxresdefault.jpg");
console.log("clip path triangle ->", "https://bennettfeely.com/clippy/");
console.log("hexagons based in ->", "https://programacion.net/files/article/20160729010743_hexagonos.jpg");
console.log("img-1 ->", "https://wallhaven.cc/w/2k2gy9");
console.log("img-2 ->", "https://wallhaven.cc/w/396lmd");
console.log("img-3 ->", "https://wallhaven.cc/w/9mgjq1");
console.log("img-4 ->", "https://wallhaven.cc/w/0wv5xx");
console.log("img-5 ->", "https://wallhaven.cc/w/nzm8ky");
console.log("img-6 ->", "https://wallhaven.cc/w/ne83mo");
console.log("img-7 ->", "https://wallhaven.cc/w/zx1x1y");
console.log("img-8 ->", "https://wallhaven.cc/w/nzmqly");
console.log("img-9 ->", "https://wallhaven.cc/w/4g33dd");
console.log("img-10 ->", "https://wallhaven.cc/w/nmzox8");
console.log("img-11 ->", "https://wallhaven.cc/w/43yq6y");
console.log("img-12 ->", "https://wallhaven.cc/w/3kdvg6");
console.log("img-13 ->", "https://wallhaven.cc/w/p8d67m");
console.log("img-14 ->", "https://wallhaven.cc/w/nzw76y");
console.log("img-15 ->", "https://wallhaven.cc/w/73ewlo");
console.log("img-16 ->", "https://wallhaven.cc/w/4dm8oo");
console.log("img-17 ->", "https://wallhaven.cc/w/0pvog3");
console.log("img-18 ->", "https://wallhaven.cc/w/nrq25j");
console.log("img-19 ->", "https://wallhaven.cc/w/3k713v");
console.log("img-20 ->", "https://wallhaven.cc/w/4y3v6d");
console.log("img-21 ->", "https://wallhaven.cc/w/0j3lem");
console.log("img-22 ->", "https://wallhaven.cc/w/mdg3x1");
console.log("img-23 ->", "https://wallhaven.cc/w/gj2wge");
console.log("img-24 ->", "https://wallhaven.cc/w/j8em9w");
console.log("img-25 ->", "https://wallhaven.cc/w/4v7gxl");
console.log("img-26 ->", "https://wallhaven.cc/w/xlyj6o");
console.log("img-27 ->", "https://wallhaven.cc/w/eyqexl");
console.log("img-28 ->", "https://wallhaven.cc/w/4vgow3");
console.log("img-29 ->", "https://wallhaven.cc/w/g8p59q");
console.log("img-30 ->", "https://wallhaven.cc/w/lmpkzr");
console.log("img-31 ->", "https://wallhaven.cc/w/01lw3w");
console.log("img-32 ->", "https://wallhaven.cc/w/0wv5dx");
console.log("img-33 ->", "https://wallhaven.cc/w/nklo5q");
console.log("img-34 ->", "https://wallhaven.cc/w/4ye5xx");
console.log("img-35 ->", "https://wallhaven.cc/w/zmdo9w");
console.log("img-38 ->", "https://wallhaven.cc/w/nmd978");
console.log("img-39 ->", "https://wallhaven.cc/w/01jywg");
console.log("img-40 ->", "https://wallhaven.cc/w/5dve28");
console.groupEnd();